platform :ios, '10.0'
inhibit_all_warnings!
 
workspace 'AgoraEducation.xcworkspace'
install! 'cocoapods', :deterministic_uuids => false, :warn_for_unused_master_specs_repo => false
 
target 'AgoraEducation' do
  use_frameworks!
  
  # for token builder
  pod 'OpenSSL-Universal', '1.0.2.17'
  
  # third libs
  pod "CocoaLumberjack",   '3.6.1'
  pod 'AliyunOSSiOS',      '2.10.8'
  pod 'SSZipArchive',      '2.4.2'
  pod 'SwifterSwift',      '5.2.0'
  pod 'SDWebImage',        '5.12.0'
  pod 'Protobuf',          '3.17.0'
  pod 'Masonry',           '1.1.0'
  pod 'Armin',             '1.1.0'
  
  # agora libs
  pod 'AgoraRtcEngine_iOS/RtcBasic', '3.7.2'
  pod 'AgoraMediaPlayer_iOS',        '1.3.0'
  pod 'Agora_Chat_iOS',              '1.0.6'
  pod 'AgoraRtm_iOS',                '1.4.8'
  pod 'Whiteboard',                  '2.16.51'
 
  # open source libs
  pod 'AgoraClassroomSDK_iOS', '2.8.30'
  pod 'AgoraEduUI',            '2.8.30'
  
  pod 'AgoraProctorSDK',       '1.0.1'
  pod 'AgoraProctorUI',        '1.0.0'
  
  pod 'AgoraWidgets',          '2.8.30'
  
  # close source libs
  pod 'AgoraUIBaseViews',      '2.8.0'
  pod 'AgoraEduCore', 	       '2.8.30'
  pod 'AgoraWidget',           '2.8.0'

  # post install, no signing for pods bundle, after xcode 14
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
